### ISSUE TITLE
Render Markdown emoji everywhere

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/ubclaunchpad.github.io-old#57]
This is what disappointment looks like

<img width="200" alt="image" src="https://user-images.githubusercontent.com/23356519/40588443-2d9d45da-6192-11e8-88e6-f96f054d1346.png">

**Comment by bfbachmann** [comment]
This is a fairly non-trivial task, and I'm not really sure it's worth it. I would actually like to avoid putting emojis in team names all-together, because it makes editing and updating teams by name through Rocket error-prone. In fact, it actually makes it near impossible for most unicode emojis that Slack supports because Slack auto-corrects unicode emojis it their `:emoji-name:` equivalent.

**Comment by bobheadxi** [comment]
There are libraries that support it - I have emoji rendering in my jekyll blog

**Comment by bfbachmann** [comment]
I guess what I'm saying it that the work required is relatively high for it's payoff. We'd have to add new option parsing rules to look for things that represent Slack emojis depending on command and context. Then we'd have to translate that plain-text into the unicode equivalent (for which there may not be a mapping, because Slack supports custom emojis), then insert into the DB. We'd also have to to the same when querying the DB.

**Comment by bobheadxi** [comment]
Slack emojis translate are the same as normal Markdown emoji - for example, `:cloud:` is ☁️ here in GitHub too. Any library that can handle Markdown emoji will work here. For example, it could see the markdown `:cloud:` and render the ☁️ appropriately. [jemoji](https://github.com/jekyll/jemoji) is one such plugin for jekyll - all we need to do is see if one exists and use it

**Comment by bfbachmann** [comment]
True, but that's not the case on our website, and my point about it being more work than it's worth still stands.

**Comment by bfbachmann** [comment]
I'm open to us building this feature, but it needs to be done properly and there are much more useful things we should do first.
